/*
  # Drop unused Stripe template tables and orphan RPC function

  ## Summary
  Removes 5 tables generated by a generic Stripe template that are never
  referenced anywhere in the project codebase. The project uses its own
  `subscriptions` and `document_packs` tables plus `companies.stripe_customer_id`
  for all Stripe logic. Also removes the `add_driver_to_company` RPC function
  which is never called from any file in the project.

  ## Tables dropped
  - `stripe_user_orders` (view/table from Stripe template, zero usage)
  - `stripe_user_subscriptions` (view/table from Stripe template, zero usage)
  - `stripe_orders` (Stripe template, zero usage)
  - `stripe_subscriptions` (Stripe template conflicts with project's own `subscriptions`)
  - `stripe_customers` (Stripe template, zero usage)

  ## Functions dropped
  - `add_driver_to_company` (RPC never called from any frontend or edge function file)

  ## Impact
  No data loss risk — these tables contain no production data and are unreferenced.
  The `subscriptions`, `document_packs`, and `companies` tables are untouched.
*/

DROP VIEW IF EXISTS stripe_user_orders CASCADE;
DROP VIEW IF EXISTS stripe_user_subscriptions CASCADE;

DROP TABLE IF EXISTS stripe_orders CASCADE;
DROP TABLE IF EXISTS stripe_subscriptions CASCADE;
DROP TABLE IF EXISTS stripe_customers CASCADE;

DROP FUNCTION IF EXISTS add_driver_to_company(uuid, uuid);
DROP FUNCTION IF EXISTS add_driver_to_company(uuid, uuid, text);
DROP FUNCTION IF EXISTS add_driver_to_company CASCADE;
